---
title: Personages die geen speler zijn (NPC)
hero_image: images/banner.png
description: Maak 3D-personages die geen speler zijn om mee te communiceren, te ontwijken en power-ups van te verzamelen
meta_title: Leer Unity | Spelontwikkeling | personages die geen speler zijn
meta_description: Leer Unity game development met de Raspberry Pi Foundation. Creëer 3D niet-speler-personages in Unity om mee te communiceren, te ontwijken en van te verzamelen.
version: 4
listed: true
copyedit: true
last_tested: '2021-03-26'
steps:
  - title: Wat ga je maken
  - title: Gamemaster-NPC
  - title: Het spel besturen
    completion:
      - engaged
  - title: NPC die patrouilleren
  - title: Volger NPC
  - title: NPC bondgenoten
    completion:
      - internal
  - title: Snelle quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Verbeter je project