title: non-player-characters
hero_image: images/banner.png
description: non-player-characters description
version: 4
listed: false
copyedit: false
last_tested: "2021-10-26"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
